spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wangxun0902
    url: jdbc:mysql://106.14.133.223/data_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8080